### ISSUE TITLE
unable to compile v12.11

### ISSUE THREAD

**Issue by drbel8** [AER-RC/LBLRTM#10]
I'm unable to compile v12.11 the log below is for linuxINTELdbl  but I've the same issue for INTELsgl 

make -f make_lblrtm  linuxINTELdbl

-----------------
  lblrtm_v12.11_linux_intel_dbl Makefile
-----------------

This Makefile was designed for the linux platform.

It uses the ifort compiler, with the following options:
      -r8 -i8 -w -Vaxlib

The source files used are as follows:

      lblrtm.f90 oprop.f90 contnm.f90 xmerge.f90 testmm.f90 lblatm.f90 lbllow.f90 postsub.f90 pltlbl.f90 lbldum.f90 solar.f90 nonlte.f90 fftscn_dbl.f90 util_linux_intel.f90 phys_consts.f90 planet_earth.f90 lblparams.f90 struct_types.f90 solar_cycle.f90

The object files used are as follows:

      lblrtm.o oprop.o contnm.o xmerge.o testmm.o lblatm.o lbllow.o postsub.o pltlbl.o lbldum.o solar.o nonlte.o fftscn_dbl.o util_linux_intel.o phys_consts.o planet_earth.o lblparams.o struct_types.o solar_cycle.o

The object file path is as follows:
      lblrtm_v12.11_linux_intel_dbl.obj

The executable will be:
../lblrtm_v12.11_linux_intel_dbl

make in progress ...

make[1]: *** No rule to make target '../src/util_linux_intel.f90', needed by 'lblrtm_v12.11_linux_intel_dbl.obj/util_linux_intel.o'.  Stop.
makefile.common:258: recipe for target 'linuxINTELdbl' failed
make: *** [linuxINTELdbl] Error 2

**Comment by pernak18** [comment]
@drbel8 did you use the `--recursive` keyword when you did a `git clone`?

**Comment by drbel8** [comment]
no, I didn't, I have to use https clone at the moment and --recursive is complaining about an issue with the public key.
nevertheless I managed to compile after cloning the aer_rt_utils
thank you
