### ISSUE TITLE
Cannot compile LNFL (source files are not in repository)

### ISSUE THREAD

**Issue by pochedls** [AER-RC/LBLRTM#11]
When I try to build LNFL, I get the following error:

```
make[1]: *** No rule to make target `util_gfortran.f90', needed by `build'.  Stop.
make: *** [linuxGNUsgl] Error 2
```

I believe this occurs because the files in [LNFL/src/](https://github.com/AER-RC/LNFL/tree/master/src) are symbolic links and not actual fortran files. When I copy in an old `util_gfortran.f90` file, I am able to compile LNFL.

**Comment by pernak18** [comment]
@pochedls when you cloned the LNFL repository, did you use the `--recursive` keyword?

**Comment by pochedls** [comment]
> @pochedls when you cloned the LNFL repository, did you use the `--recursive` keyword?

I did not, I just fixed this and was able to compile. Thank you for replying so quickly!
