### ISSUE TITLE
N2 continuum absorption independent of N2 column density?

### ISSUE THREAD

**Issue by asmette** [AER-RC/LBLRTM#13]
The N2 continuum absorption appears independent of the N2 column density, to the point that putting the N2 column density to 0 still leads to N2 continuum absorption!

If my understanding of the code is correct, looking at contnm.f90 line 216, I find that, for the continuum calculation, it is related to H2O and O2.

Excuse my ignorance, but shouldn't it we have 
`x_vmr_n2 = wk(22)/wtot `
 instead of the current
`x_vmr_n2 = 1. - x_vmr_h2o - x_vmr_o2 `?

I guess there is a reason this line exists. However, I use LBLRTM to interpret ground based spectra and determine molecular abundances of various molecules: hence, this feature does not suit my needs, if I understand the code correctly.

**Comment by kcadyper** [comment]
To asmette: we need to define_x_vmrr_n2 as we do to get correct values for the O2 continuum. In order to turn of the N2 continuum you can do the following:
1. Set ICNTNM=6
2. Use the continuum scale factors in record 1.2a to scale the continuum for all desired molecules: e.g., set XN2CN to zero to turn the N2 continuum off
Hope this helps!

**Comment by asmette** [comment]
Hi Karen, 

Thanks for the answer.

I am still puzzled because I do not understand the physics behind this choice. Note that I do not wish to have the N2 continuum off, just that it depends on the N2 column density, not on the column density of O2 or CO2! 

I will explore the option ICNTNM=6. It looks like I would get what I wish by using XN2CN set to 1.

Regards, Alain

**Comment by kcadyper** [comment]
Hi, Alain

Our method of calculating x_vmr_n2  provides  the number of  molecules that are neither O2 nor H2O,  which is needed for both the O2 and N2 continuum calculations, as O2 and H2O have collision efficiencies with N2 (and H2O with O2) that are different from the N2 or O2 self collision efficiencies.  We could simply do as you suggest (x_vmr_n2 = wk(22)/wtot) but many users often don't specify N2 amounts in their inputs, which lead to an x_vmr_n2 of zero and incorrect results. If you are specifying N2 in your inputs you could modify the code as you suggested, Let us know how it goes.

**Comment by kcadyper** [comment]
Note that LBL reads in the user specified gas amounts and pressure and temperature, calculates the total number of molecules in each from the latter two parameters, subtracts the  number of specified molecules, and calls the result the broadening gas, which has no line  absorption but impacts the line shape calculations.

**Comment by pernak18** [comment]
all: can this issue be closed?
