### ISSUE TITLE
Example Codes/Tape files for LBLRTM/LNFL

### ISSUE THREAD

**Issue by MadFisa** [AER-RC/LBLRTM#17]
Hi,
I have been looking around for example tape files for LNFL and LBLRTM and am unable to find it. Some of the old documents suggest that it used to be bundled with the .tar files before the shift to github.  Is there a way to find some sample codes to understand and use LBLRTM/LNFL?

**Comment by MadFisa** [comment]
Never mind. I just found the example codes in the release pages. Maybe it could be made more clear in the README.md where to find them. Maybe adding a section on how to run and use the example codes for testing, after the instructions for installation could help.

**Comment by pernak18** [comment]
thank you @MadFisa! we currently have a [section](https://github.com/AER-RC/LBLRTM#tests) of the top-level `README.md` that is dedicated to the tests that does the minimum and points to the binary tar package. it's a pretty big README and a small section, so it gets buried. with regard to running the examples, we have a `README.setup` in the v12.10 run examples that apparently did not propagate to v12.11, so for now i'll include it here:

> Users should create a working directory (wdir) and place the LBLRTM, LNFL and line packages in this directory. 
> This will facilitate the running of the exmaple cases and other runs the user wishes to do.
> 
> Once the packages are unzipped and untarred, wdir should have three top level directories:
> 
> lblrtm			lnfl  		aer_v_3.8
> 
> Follow the following steps to run the examples:
> 
> 1. cd to lnfl/build and build the lnfl executable
> 
> 2. cd to lblrtm/build and build the lblrtm executable
> 
> 3. cd to lblrtm/run_examples/TAPE3_files and run run_lnfl.pl to create the TAPE3s required for the examples
> 
> 4. cd to each example in lblrtm/run_examples and run the script_run_example.pl to create output (files tagged
> with _test) that can be compared to the output provided by AER (files tagged with _ex).
