### ISSUE TITLE
How to obtain band integrated values for TOA reflectance calculations?

### ISSUE THREAD

**Issue by varisht-tathya** [AER-RC/LBLRTM#20]
I am trying to calculate TOA reflectance for Sentinel 2 Band 12. I tried using the merge flags while generating the TAPE5 file for LBLRTM, however I still get transmittance / radiance for individual wavelengths. Are there any other flags I need to consider? I am running them with the solar flag on, and have generated the SOLAR.RAD file from the solar-source-function repo. Are there any examples for this sort of calculation?

**Comment by pernak18** [comment]
@kcadyper @varisht-tathya could you provide a distilled version of your email thread on what the solution is?

please and thanks!

**Comment by kcadyper** [comment]
I provided Varisht with instructions for running a downlooking solar case and some suggestions for getting band integrated values

**Comment by varisht-tathya** [comment]
kcadyper has helped me in running the LBLRTM model using the solar example and provided suggestions like applying the satellite response function on the output to get the band integrated values.

**Comment by pernak18** [comment]
> Hi, Varisht
> 
>  
> 
> Thank you for your interest in LBLRTM. LBLRTM does monochromatic calculations, but also can apply the instrument line shape to the monochromatic output to generate band values. See the SCANFN and FFTSCn options in the instructions.

> You should add another run to apply the desired scan function to TAPE13, the final output of the three runs. Let me know if you need help with that. There is no need to use any MERGE options. If you just want the total TOA radiance, with no instrument function applied, you can just add up the radiances from the TAPE13.
> 
>  
> 
> I am not very familiar with the Python tools but after taking a look you should be able to read the TAPE13 with readTAPE12 with filetype=0.

> Integrating would provide an estimate, but I think to get an accurate value you would have to apply the Sentinel2 instrument line shape (ILS) to the output on TAPE13, then integrate

there was a lot of back and forth, so i'm sure i missed some details, but i think this summarizes most of the solution?
