### ISSUE TITLE
x

### ISSUE THREAD

**Issue by lusishui** [AER-RC/LBLRTM#24]

**Comment by pernak18** [comment]
@lusishui should the title of this issue be "NO ISOTOPE INFO ON LINFIL" and the description be:

> Hello,
> I've successfully built LBLRTM and LNFL in single precision. The TARGET environment I chose is "linuxGNUsgl". However, when I tried to run examples in the "run_example_user_defined_upwelling" folder to validate the building of LBLRTM, the terminal always showed "STOP PRLNHD - NO ISOTOPE INFO ON LINFIL". I've linked TAPE3 file to TAPE3_aer_v_3.8_ex_ir in TAPE3_files. It seems that the LBLRTM cannot successfully read the header information of the line file produced by LNFL. Can you provide some help?
> The version: LBLRTM 12.13, LNFL v3.2

or have you already solved the issue?

**Comment by lusishui** [comment]
Hi pernak18,
I've solved the Problem. LNFL can only be compiled in single precision?
Thanks.

**Comment by pernak18** [comment]
that's correct. sorry for the inconvenience. i'll close this issue, then. thanks for your interest in our models!
