### ISSUE TITLE
multiple profiles

### ISSUE THREAD

**Issue by FanliLiu** [AER-RC/LBLRTM#25]
Hi. Is it possible to write multiple profiles in one TAPE5? And can it output multiple results (like radiances or optical depths) in one file (like TAPE27 or ODdeflt*)? I tried to copy the content in TAPE5 twice and then run LBLRTM, but it didn't output twice.

**Comment by pernak18** [comment]
@FanliLiu you'll need a separate run for each profile. typically, i have a separate directory for each profile, then stage the inputs i need in those working directories with symbolic links to the `TAPE3`, `TAPE5`, `xs`, `FSCDXS`, `EMISSIVITY`, `REFLECTIVITY`, etc. as needed. one feature of LBL is that it assumes naming conventions for files that might change with different profiles (`TAPE3` and `TAPE5` are two examples), so if you run for two profiles in the same directory, your inputs and outputs will get overwritten.

if you'd like an example, i've written a [driver](https://github.com/ReFRACtor/GENOD/blob/master/run_RT_Ref_OD.py) and [associated module](https://github.com/ReFRACtor/GENOD/blob/master/GENOD_compute.py) that runs LBL for a few profiles in series. i can dig up some parallelized examples too, if that would help.

**Comment by FanliLiu** [comment]
@pernak18 Thank you. I will try.
