### ISSUE TITLE
Issue and Fix with comipiling the latest clone

### ISSUE THREAD

**Issue by wilsonr1** [AER-RC/LBLRTM#30]
Hi everyone,

I wanted to summarize my issue with cloning LBLRTM and building it from this repository.   I am a little new to working with github so I ended up cloning the master branch instead of the latest release.  I attempted to build it on a linux machine using gfortran to build it.  At first It wouldn't build it because it couldn't find the netcdf libraries.  I tried to put in the location of my netcdf library in the addlibs.inc file.  However it still couldn't find -libnetcdff.  The way my netcdf was built on my server was that there was a netcdf c version, and a separate netcdf fortran version.  There wasn't a straight forward method to edit the addlibs.inc file I saw if the needed netcdf libraries were in different locations.  So I eventually went to the netcdf bin directory, and typed the ./nc_config -libs command and got the needed library linkages to run netcdf.  I edited the LD_FLAG in make_lblrtm to point to the exact locations on my machine where all the netcdf libraries were. I also had to include the hdf library.  This built lblrtm.  To get it to run I had to make sure the hdf library with in my library path.

**Comment by pernak18** [comment]
thanks @wilsonr1! i'll close this now since you have resolved it yourself.
