### ISSUE TITLE
the issue of compile

### ISSUE THREAD

**Issue by dengwanxia1991** [AER-RC/LBLRTM#41]
When I carry out "gmake -f make_lblrtm linuxGNUsgl", I get the problem as follows:  Function 'nf_get_var' at (1) has no Implicit type  ../src/read_module.f90:164:39:

**Comment by pernak18** [comment]
@kcadyper can you help @dengwanxia1991 here? i *think* the answer is to change `NETCDF` to "no" in [`addlibs.inc`](https://github.com/AER-RC/LBLRTM/blob/master/build/addlibs.inc#L7), but i don't know if that is producing the error they have reported.

please and thanks

**Comment by kcadyper** [comment]
Starting with v12.14 LBLRTM reads the water vapor continuum parameters from a netCDF file. This implies that  the compiler needs to know where the netCDF FORTRAN libraries and include files are. This is done by setting these paths in the build/addlibs.inc file. Note that the libraries and include files must be compatible with the version of gfortran you are using.  If you don't have this information please ask your IT people for help.

**Comment by dengwanxia1991** [comment]
> Starting with v12.14 LBLRTM reads the water vapor continuum parameters from a netCDF file. This implies that the compiler needs to know where the netCDF FORTRAN libraries and include files are. This is done by setting these paths in the build/addlibs.inc file. Note that the libraries and include files must be compatible with the version of gfortran you are using. If you don't have this information please ask your IT people for help.

Thanks for your reply. When I carry out the compile, I have added the path of netCDF FORTRAN libraries and include files into the addlibs.inc file.  The gfortran installed is 11.3.0. And the version of netCDF is 4.9.2. The version of netCDF FORTRAN is 4.6.0.

**Comment by dengwanxia1991** [comment]
> lblrtm

And now, By deleting three sentences containing the string "nf_get_va" in the read_module.f90 file, the complie works. But there are still some warnings , e.g., type mismatch in argument 'fnct1' at(1); passed REAL (4) to COMPLEX (4).

**Comment by pernak18** [comment]
@dengwanxia1991 warnings are expected, particularly with `gfortran`. you should be able to proceed. thank you for interest in LBLRTM

**Comment by kcadyper** [comment]
The warnings are not a problem; but deleting the nf_get_var lines will break the code. I would try using an older version of gfortran; we are using gfortran 4.8.5.
