### ISSUE TITLE
Compilation error in build folder in Ubuntu

### ISSUE THREAD

**Issue by vijaykumarsagar** [AER-RC/LBLRTM#43]
Hi everyone, I am trying to install LBLRTM model in Ubuntu 20.04 sysem. I am getting following error during compilation:
`make -f make_lblrtm linuxGNUdb`
`Warning: Named COMMON block ‘ifil’ at (1) shall be of the same size as elsewhere (144 vs 152 bytes)
make[1]: *** No rule to make target '../src/util_gfortran.f90', needed by 'lblrtm_v12.15.1_linux_gnu_dbl.obj/util_gfortran.o'.  Stop.
make: *** [makefile.common:218: linuxGNUdbl] Error 2
`
I have followed the information given at [here](https://github.com/AER-RC/LBLRTM/issues/34) but could not solve it. Can you help me to solve this issue.

Thanks and regards,
Vijay Sagar 

[compilation_text.txt](https://github.com/AER-RC/LBLRTM/files/11635503/compilation_text.txt)

**Comment by pernak18** [comment]
thanks @vijaykumarsagar . did you do a clone with `--recursive`?

**Comment by vijaykumarsagar** [comment]
> thanks @vijaykumarsagar . did you do a clone with `--recursive`?
Thanks @pernak18 for your response. No, I have downloaded model code zip file from [github](https://codeload.github.com/AER-RC/LBLRTM/zip/refs/heads/master).

**Comment by vijaykumarsagar** [comment]
Thanks @pernak18. It worked when I tried with `--recursive`. I will proceed to the next step. Thank you for your instant help.
