### ISSUE TITLE
Question about  Jacobians/derivatives

### ISSUE THREAD

**Issue by qz123** [AER-RC/LBLRTM#46]
in the **Frequently Asked Questions**  mentioned "A PowerPoint document with plots showing the results from the two scripts has been included" in the last paragraph,but i didn't find it。can you tell me?

**Comment by kcadyper** [comment]
Hi. We apologize for this issue. The FAQ has not been updated in some time, and mistakenly cites a PowerPoint document that does not exist.

**Comment by qz123** [comment]
ok thank you for your reply！





------------------ Original ------------------
From: kcadyper ***@***.***&gt;
Date: Tue,Jul 25,2023 9:54 PM
To: AER-RC/LBLRTM ***@***.***&gt;
Cc: qz123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [AER-RC/LBLRTM] Question about  Jacobians/derivatives (Issue #46)





 
Hi. We apologize for this issue. The FAQ has not been updated in some time, and mistakenly cites a PowerPoint document that does not exist.
